### ISSUE TITLE
how to install and use ?

### ISSUE THREAD

**Issue by tissatussa** [ageneau/scid_node_addon#1]
in your readme you explain how to install SCID by npm .. am i right?  But i already have SCID installed on my Xubuntu 20.04 .. but i can not run a .js engine like Lozza 2.0 in SCID : using 'node' as command and the path to the .js file as parameter, SCID gives an error .. this concept DOES work in CuteChess though .. how can i use your script ?  Do i even need it ?

**Comment by ageneau** [comment]
Hi. This npm package doesn't install the full scid program, only the C library that scid is built upon. It's meant for things like scripting. If you want to install scid you should install it from http://scid.sourceforge.net/
